version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./html:/usr/share/nginx/html:ro

volumes:
  pgdata:

networks:
  backend:
